/*
 * Regenerates loc/en-us.js.
 *
 * The welcome text a new web part shows is kept in samples/welcome.md so it can
 * be edited as markdown (and previewed by the demo) instead of as an escaped
 * one-line JavaScript string. Run `node scripts/build-strings.js` after editing
 * either that file or the STRINGS table below.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const sample = fs.readFileSync(path.join(root, 'samples', 'welcome.md'), 'utf8');

const STRINGS = {
  ContentPageDescription: 'Choose where the markdown comes from.',
  ContentGroupName: 'Content',
  ContentSourceLabel: 'Source',
  MarkdownContentLabel: 'Markdown',
  MarkdownContentDescription: 'Typed here and stored with the web part. Good for short content; use a library file for anything you want to version.',
  FileUrlLabel: 'File URL',
  FileUrlDescription: 'Any URL that returns markdown. SharePoint URLs are requested with your sign-in; other sites must allow cross-origin requests.',
  LibraryLabel: 'Document library',
  FolderLabel: 'Folder',
  FileLabel: 'Markdown file',
  AutoRefreshLabel: 'Reload when the file changes',
  VersionHistoryLabel: 'Show version history button',

  AppearancePageDescription: 'Theme and reading options.',
  ThemeGroupName: 'Theme',
  ThemeFamilyLabel: 'Theme',
  ColorModeLabel: 'Colour mode',
  ThemeSwitcherLabel: 'Let readers switch theme',
  ThemeHint: 'GitHub, Obsidian and VS Code each bring their own typography, code block styling, callout shape and syntax colours in both light and dark.',
  ReadingGroupName: 'Reading',
  ContentWidthLabel: 'Content width',
  DensityLabel: 'Spacing',
  TextSizeLabel: 'Text size',
  ToolbarVisibilityLabel: 'Show toolbar',
  PrintButtonLabel: 'Show print button',
  ShowSourceInfoLabel: 'Show file name and last updated',
  CodeGroupName: 'Code blocks',
  SyntaxHighlightingLabel: 'Syntax highlighting',
  CodeHeaderLabel: 'Show language header',
  LineNumbersLabel: 'Show line numbers',
  WrapCodeLabel: 'Long lines',
  CodeSizeLabel: 'Code text size',

  FeaturesPageDescription: 'Turn individual rendering features on or off.',
  FeaturesGroupName: 'Features',
  TocPositionLabel: 'Table of contents',
  TocLevelLabel: 'Deepest heading in the contents',
  AnchorsLabel: 'Heading link anchors',
  MermaidLabel: 'Mermaid diagrams',
  MathLabel: 'Math (KaTeX)',
  AllowHtmlLabel: 'Allow raw HTML in markdown',
  AllowHtmlHint: 'Leave off unless you trust everyone who can edit the source. With it on, HTML in the markdown is rendered as-is.',
  SaveShortcutHint: 'Ctrl+S saves while the editor has focus.',

  SampleContent: sample
};

const banner = [
  '// Generated by scripts/build-strings.js - edit that file or samples/welcome.md,',
  '// then run `node scripts/build-strings.js`.',
  ''
].join('\n');

const body = `define([], function () {\n  return ${JSON.stringify(STRINGS, null, 2).replace(/\n/g, '\n  ')};\n});\n`;

fs.writeFileSync(path.join(root, 'src', 'webparts', 'markdownFormatter', 'loc', 'en-us.js'), banner + body);
console.log('Wrote loc/en-us.js');
